//#define _DEBUG_
#define THRESHOLD 188
#define INVOICE_SHORTEST_LINE_SIZE 500
#define ACCNT_SHORTEST_LINE_SIZE 100
//#define RECT_DISTANCE_Y_OFFSET 10
#define LINE_DISTANCE_X_OFFSET 10
#define WORD_HALF_HEIGHT 15

//error 

#define	ERROR_COLUMN_NOT_FOUND "ErrScan001"

#define	ERROR_HLINE_NOT_FOUND "ErrScan002"